//! Test fixture: voice-band filter with band edges shifted by +100 Hz (SC-008).
//!
//! GENERATED by tools/filter-design/design_voiceband.py — do not edit.
//! Regenerate with: `uv run tools/filter-design/design_voiceband.py --shift-hz 100 --emit-fixture <path>`
//!
//! Design (research.md R-07), at the 8 kHz device rate (A-001):
//! - high-pass: Butterworth, order 5, -3 dB at 400 Hz
//! - low-pass: elliptic, order 6, 0.1 dB ripple, 40 dB stopband, edge 3480 Hz
//! - gain normalized to 0 dB at 1 kHz (A-015); minimum-phase (A-016)
//! - G.712-like voice-band template, shared by stages 4 and 10 (A-002, A-014)
//!
//! Each section is `[b0, b1, b2, a1, a2]` with `a0 = 1`, stored as exact bit patterns
//! so the coefficients are identical on every platform (R-04).

/// Second-order sections of the voice-band stage filter, applied in order.
#[rustfmt::skip]
pub const SHIFTED_SOS: [[f64; 5]; 6] = [
    // section 0: high-pass
    [
        f64::from_bits(0x3fe36377b6a706d4), // b0 = 6.05892044776022320e-01
        f64::from_bits(0xbfe36377b6a706d4), // b1 = -6.05892044776022320e-01
        f64::from_bits(0x0000000000000000), // b2 = 0.00000000000000000e+00
        f64::from_bits(0xbfe73fd61d9df544), // a1 = -7.26542528005361010e-01
        f64::from_bits(0x0000000000000000), // a2 = 0.00000000000000000e+00
    ],
    // section 1: high-pass
    [
        f64::from_bits(0x3ff0000000000000), // b0 = 1.00000000000000000e+00
        f64::from_bits(0xc000000000000000), // b1 = -2.00000000000000000e+00
        f64::from_bits(0x3ff0000000000000), // b2 = 1.00000000000000000e+00
        f64::from_bits(0xbff858d80f69dd9b), // a1 = -1.52169042607224614e+00
        f64::from_bits(0x3fe3333333333336), // a2 = 6.00000000000000311e-01
    ],
    // section 2: high-pass
    [
        f64::from_bits(0x3ff0000000000000), // b0 = 1.00000000000000000e+00
        f64::from_bits(0xc000000000000000), // b1 = -2.00000000000000000e+00
        f64::from_bits(0x3ff0000000000000), // b2 = 1.00000000000000000e+00
        f64::from_bits(0xbffbc7ed2b0af1b4), // a1 = -1.73631016553472950e+00
        f64::from_bits(0x3fea6bd80f395ad8), // a2 = 8.25664548620660632e-01
    ],
    // section 3: low-pass
    [
        f64::from_bits(0x3fe14fe8ed2dd4c3), // b0 = 5.41004622688568637e-01
        f64::from_bits(0x3ff1331164f7e4c8), // b1 = 1.07496776047473652e+00
        f64::from_bits(0x3fe14fe8ed2dd4c1), // b2 = 5.41004622688568415e-01
        f64::from_bits(0x3ff2af8ce447e0ca), // a1 = 1.16785897419144868e+00
        f64::from_bits(0x3fd9636ba11bf614), // a2 = 3.96693141301370789e-01
    ],
    // section 4: low-pass
    [
        f64::from_bits(0x3ff0000000000000), // b0 = 1.00000000000000000e+00
        f64::from_bits(0x3ffeced9d672c977), // b1 = 1.92550071495915431e+00
        f64::from_bits(0x3ff0000000000002), // b2 = 1.00000000000000044e+00
        f64::from_bits(0x3ffa3919598a0382), // a1 = 1.63894019104211042e+00
        f64::from_bits(0x3fe9d6902f7e67e2), // a2 = 8.07441799889826450e-01
    ],
    // section 5: low-pass
    [
        f64::from_bits(0x3ff0000000000000), // b0 = 1.00000000000000000e+00
        f64::from_bits(0x3ffe3a9d196a8033), // b1 = 1.88930997779972354e+00
        f64::from_bits(0x3ff0000000000001), // b2 = 1.00000000000000022e+00
        f64::from_bits(0x3ffcf2b71b950f85), // a1 = 1.80925665640185795e+00
        f64::from_bits(0x3feeb71315053bd4), // a2 = 9.59847966247134199e-01
    ],
];
