//! AGC detector Hilbert FIR coefficients (signal-chain stage 3, spec 002).
//!
//! GENERATED by tools/filter-design/design_hilbert.py — do not edit.
//! Regenerate with: `uv run tools/filter-design/design_hilbert.py`
//!
//! Design (specs/002-agc/research.md R-03), at the 8 kHz device rate (A-001):
//! - equiripple type-III Hilbert transformer, 63 taps, passband 250-3750 Hz
//! - |H| within ±0.01 dB from 300 to 3400 Hz
//! - forms the analytic envelope of the AGC level detector (A-019, R-02)
//! - all design values are engineering targets (002 R-15)
//!
//! Taps are antisymmetric, and every odd-index tap (including the centre) is exactly 0,
//! so only the 32 even-index taps need multiplying. Each coefficient is
//! stored as an exact bit pattern so it is identical on every platform (001 R-04).

/// Hilbert FIR taps, `h[0]` first. The filter's delay is 31 samples.
#[rustfmt::skip]
pub(crate) const AGC_HILBERT: [f64; 63] = [
    f64::from_bits(0x3f48b20721ad851c), // h[0] = 7.53644449428633994e-04
    f64::from_bits(0x0000000000000000), // h[1] = 0.00000000000000000e+00
    f64::from_bits(0x3f5433f881c18954), // h[2] = 1.23309391258226864e-03
    f64::from_bits(0x0000000000000000), // h[3] = 0.00000000000000000e+00
    f64::from_bits(0x3f61f2b6c31bb19f), // h[4] = 2.19093032580115711e-03
    f64::from_bits(0x0000000000000000), // h[5] = 0.00000000000000000e+00
    f64::from_bits(0x3f6d655dba4e7a80), // h[6] = 3.58837419703600391e-03
    f64::from_bits(0x0000000000000000), // h[7] = 0.00000000000000000e+00
    f64::from_bits(0x3f76ba4cc75db2e2), // h[8] = 5.54876319607153397e-03
    f64::from_bits(0x0000000000000000), // h[9] = 0.00000000000000000e+00
    f64::from_bits(0x3f80d4eea9b70e5d), // h[10] = 8.21863608769673494e-03
    f64::from_bits(0x0000000000000000), // h[11] = 0.00000000000000000e+00
    f64::from_bits(0x3f881ff3b74ecd42), // h[12] = 1.17796936336619397e-02
    f64::from_bits(0x0000000000000000), // h[13] = 0.00000000000000000e+00
    f64::from_bits(0x3f90dcbaecf15f42), // h[14] = 1.64670188063091930e-02
    f64::from_bits(0x0000000000000000), // h[15] = 0.00000000000000000e+00
    f64::from_bits(0x3f97266e8fca3b2c), // h[16] = 2.26075434935026215e-02
    f64::from_bits(0x0000000000000000), // h[17] = 0.00000000000000000e+00
    f64::from_bits(0x3f9f6f635feaf2e4), // h[18] = 3.06983496945915230e-02
    f64::from_bits(0x0000000000000000), // h[19] = 0.00000000000000000e+00
    f64::from_bits(0x3fa54910c7cc24a6), // h[20] = 4.15730708974220570e-02
    f64::from_bits(0x0000000000000000), // h[21] = 0.00000000000000000e+00
    f64::from_bits(0x3fad13d50872d37c), // h[22] = 5.67919323743017734e-02
    f64::from_bits(0x0000000000000000), // h[23] = 0.00000000000000000e+00
    f64::from_bits(0x3fb4678e25b5ebd0), // h[24] = 7.97051279131857360e-02
    f64::from_bits(0x0000000000000000), // h[25] = 0.00000000000000000e+00
    f64::from_bits(0x3fbe7bb816325c40), // h[26] = 1.19075303477402805e-01
    f64::from_bits(0x0000000000000000), // h[27] = 0.00000000000000000e+00
    f64::from_bits(0x3fca8473be30088c), // h[28] = 2.07167117943815149e-01
    f64::from_bits(0x0000000000000000), // h[29] = 0.00000000000000000e+00
    f64::from_bits(0x3fe4514e50992ada), // h[30] = 6.34925038736891212e-01
    f64::from_bits(0x0000000000000000), // h[31] = 0.00000000000000000e+00
    f64::from_bits(0xbfe4514e50992ada), // h[32] = -6.34925038736891212e-01
    f64::from_bits(0x0000000000000000), // h[33] = 0.00000000000000000e+00
    f64::from_bits(0xbfca8473be30088c), // h[34] = -2.07167117943815149e-01
    f64::from_bits(0x0000000000000000), // h[35] = 0.00000000000000000e+00
    f64::from_bits(0xbfbe7bb816325c40), // h[36] = -1.19075303477402805e-01
    f64::from_bits(0x0000000000000000), // h[37] = 0.00000000000000000e+00
    f64::from_bits(0xbfb4678e25b5ebd0), // h[38] = -7.97051279131857360e-02
    f64::from_bits(0x0000000000000000), // h[39] = 0.00000000000000000e+00
    f64::from_bits(0xbfad13d50872d37c), // h[40] = -5.67919323743017734e-02
    f64::from_bits(0x0000000000000000), // h[41] = 0.00000000000000000e+00
    f64::from_bits(0xbfa54910c7cc24a6), // h[42] = -4.15730708974220570e-02
    f64::from_bits(0x0000000000000000), // h[43] = 0.00000000000000000e+00
    f64::from_bits(0xbf9f6f635feaf2e4), // h[44] = -3.06983496945915230e-02
    f64::from_bits(0x0000000000000000), // h[45] = 0.00000000000000000e+00
    f64::from_bits(0xbf97266e8fca3b2c), // h[46] = -2.26075434935026215e-02
    f64::from_bits(0x0000000000000000), // h[47] = 0.00000000000000000e+00
    f64::from_bits(0xbf90dcbaecf15f42), // h[48] = -1.64670188063091930e-02
    f64::from_bits(0x0000000000000000), // h[49] = 0.00000000000000000e+00
    f64::from_bits(0xbf881ff3b74ecd42), // h[50] = -1.17796936336619397e-02
    f64::from_bits(0x0000000000000000), // h[51] = 0.00000000000000000e+00
    f64::from_bits(0xbf80d4eea9b70e5d), // h[52] = -8.21863608769673494e-03
    f64::from_bits(0x0000000000000000), // h[53] = 0.00000000000000000e+00
    f64::from_bits(0xbf76ba4cc75db2e2), // h[54] = -5.54876319607153397e-03
    f64::from_bits(0x0000000000000000), // h[55] = 0.00000000000000000e+00
    f64::from_bits(0xbf6d655dba4e7a80), // h[56] = -3.58837419703600391e-03
    f64::from_bits(0x0000000000000000), // h[57] = 0.00000000000000000e+00
    f64::from_bits(0xbf61f2b6c31bb19f), // h[58] = -2.19093032580115711e-03
    f64::from_bits(0x0000000000000000), // h[59] = 0.00000000000000000e+00
    f64::from_bits(0xbf5433f881c18954), // h[60] = -1.23309391258226864e-03
    f64::from_bits(0x0000000000000000), // h[61] = 0.00000000000000000e+00
    f64::from_bits(0xbf48b20721ad851c), // h[62] = -7.53644449428633994e-04
];
