//! Voice-band stage filter coefficients (signal-chain stages 4 and 10).
//!
//! GENERATED by tools/filter-design/design_voiceband.py — do not edit.
//! Regenerate with: `uv run tools/filter-design/design_voiceband.py`
//!
//! Design (research.md R-07), at the 8 kHz device rate (A-001):
//! - high-pass: Butterworth, order 5, -3 dB at 300 Hz
//! - low-pass: elliptic, order 6, 0.1 dB ripple, 40 dB stopband, edge 3380 Hz
//! - gain normalized to 0 dB at 1 kHz (A-015); minimum-phase (A-016)
//! - G.712-like voice-band template, shared by stages 4 and 10 (A-002, A-014)
//!
//! Each section is `[b0, b1, b2, a1, a2]` with `a0 = 1`, stored as exact bit patterns
//! so the coefficients are identical on every platform (R-04).

/// Second-order sections of the voice-band stage filter, applied in order.
#[rustfmt::skip]
pub(crate) const VOICEBAND_SOS: [[f64; 5]; 6] = [
    // section 0: high-pass
    [
        f64::from_bits(0x3fe608868b1abb49), // b0 = 6.88540717781372824e-01
        f64::from_bits(0xbfe608868b1abb49), // b1 = -6.88540717781372824e-01
        f64::from_bits(0x0000000000000000), // b2 = 0.00000000000000000e+00
        f64::from_bits(0xbfe93a0d54993910), // a1 = -7.88336434585092505e-01
        f64::from_bits(0x0000000000000000), // a2 = 0.00000000000000000e+00
    ],
    // section 1: high-pass
    [
        f64::from_bits(0x3ff0000000000000), // b0 = 1.00000000000000000e+00
        f64::from_bits(0xc000000000000000), // b1 = -2.00000000000000000e+00
        f64::from_bits(0x3ff0000000000000), // b2 = 1.00000000000000000e+00
        f64::from_bits(0xbffa2c3d2214360e), // a1 = -1.63580048858728189e+00
        f64::from_bits(0x3fe5d5413886fed2), // a2 = 6.82282076268132309e-01
    ],
    // section 2: high-pass
    [
        f64::from_bits(0x3ff0000000000000), // b0 = 1.00000000000000000e+00
        f64::from_bits(0xc000000000000000), // b1 = -2.00000000000000000e+00
        f64::from_bits(0x3ff0000000000000), // b2 = 1.00000000000000000e+00
        f64::from_bits(0xbffd05aff0885feb), // a1 = -1.81388849218455550e+00
        f64::from_bits(0x3febb19b45be03aa), // a2 = 8.65430484977072867e-01
    ],
    // section 3: low-pass
    [
        f64::from_bits(0x3fdec91523b72524), // b0 = 4.81023106458979166e-01
        f64::from_bits(0x3fee7f655b5bce6a), // b1 = 9.53051260409165879e-01
        f64::from_bits(0x3fdec91523b72524), // b2 = 4.81023106458979166e-01
        f64::from_bits(0x3ff07a35d3b25422), // a1 = 1.02983648962004581e+00
        f64::from_bits(0x3fd5533930b1f53c), // a2 = 3.33204553178649610e-01
    ],
    // section 4: low-pass
    [
        f64::from_bits(0x3ff0000000000000), // b0 = 1.00000000000000000e+00
        f64::from_bits(0x3ffe4c85807d870b), // b1 = 1.89368200484790594e+00
        f64::from_bits(0x3ff0000000000001), // b2 = 1.00000000000000022e+00
        f64::from_bits(0x3ff8b35ce8714d19), // a1 = 1.54378977582820753e+00
        f64::from_bits(0x3fe8e09c7b0e7d18), // a2 = 7.77418365807451828e-01
    ],
    // section 5: low-pass
    [
        f64::from_bits(0x3ff0000000000000), // b0 = 1.00000000000000000e+00
        f64::from_bits(0x3ffd7b827d10a4ae), // b1 = 1.84265374043961172e+00
        f64::from_bits(0x3ff0000000000000), // b2 = 1.00000000000000000e+00
        f64::from_bits(0x3ffbd9155b9004d0), // a1 = 1.74049888388281104e+00
        f64::from_bits(0x3fee7d64ba9a4e6c), // a2 = 9.52806820353044426e-01
    ],
];
