/*
 * rr_dr60.h — C API for rr-dr60-emu, a software emulator of the Panasonic RR-DR60 voice
 * recorder's audio signal chain. GENERATED by cbindgen from crates/rr_dr60_ffi — do not edit.
 *
 * Contract (specs/001-pipeline-skeleton/contracts/c-api.md):
 *  1. Errors are values. No function aborts or unwinds into the caller. A caught internal
 *     error returns RR_DR60_STATUS_INTERNAL_ERROR and poisons the handle until
 *     rr_dr60_reset (or rr_dr60_reconfigure) succeeds.
 *  2. A failed call changes nothing: out-parameters are untouched and state is unchanged.
 *     Exception: out_info in rr_dr60_process and rr_dr60_process_with_events is always written
 *     when not NULL, so a host that only checks `produced` never reads a stale count.
 *  3. The caller owns all buffers; the library never keeps a pointer after a call returns.
 *     Using a handle after rr_dr60_destroy is undefined behavior.
 *  4. A handle must not be used by two threads at the same time; separate handles are
 *     independent.
 *  5. RrDr60Settings only grows at the end; always start from rr_dr60_settings_default().
 *
 * Real-time safe: rr_dr60_process, rr_dr60_process_with_events, rr_dr60_max_events,
 *   rr_dr60_reset, rr_dr60_latency_samples, rr_dr60_settings_validate.
 * Not real-time safe (allocate): rr_dr60_create, rr_dr60_destroy, rr_dr60_reconfigure.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef RR_DR60_H
#define RR_DR60_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// Library major version (equal to the Rust crate's).
#define RR_DR60_VERSION_MAJOR 0

// Library minor version.
#define RR_DR60_VERSION_MINOR 3

// Library patch version.
#define RR_DR60_VERSION_PATCH 0

// Result of every fallible C API call.
enum RrDr60Status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // Success.
  RR_DR60_STATUS_OK = 0,
  // A required pointer was NULL.
  RR_DR60_STATUS_NULL_POINTER = 1,
  // `host_rate_hz` is not a supported host rate.
  RR_DR60_STATUS_UNSUPPORTED_HOST_RATE = 2,
  // Invalid tap value, too-small `struct_size`, or partially overlapping buffers.
  RR_DR60_STATUS_INVALID_ARGUMENT = 3,
  // An internal error (a caught panic). The handle is poisoned until `rr_dr60_reset`.
  RR_DR60_STATUS_INTERNAL_ERROR = 4,
  // An AGC or VAS setting is out of range or not finite (spec 002 FR-011, spec 003 FR-012).
  // `rr_dr60_settings_validate` names it.
  RR_DR60_STATUS_INVALID_SETTING = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum RrDr60Status RrDr60Status;
#else
typedef int32_t RrDr60Status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Names the offending field for `rr_dr60_settings_validate` (spec 002 US2 AS5).
enum RrDr60SettingField
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // The settings are valid.
  RR_DR60_SETTING_FIELD_NONE = 0,
  // `host_rate_hz` is not a supported rate.
  RR_DR60_SETTING_FIELD_HOST_RATE = 1,
  // `tap` is not an `RrDr60Tap` value (status `INVALID_ARGUMENT`).
  RR_DR60_SETTING_FIELD_TAP = 2,
  // `struct_size` is smaller than `sizeof(RrDr60Settings)` of this library version.
  RR_DR60_SETTING_FIELD_STRUCT_SIZE = 3,
  // `agc_target_dbfs` is outside -30 to 0, or not finite.
  RR_DR60_SETTING_FIELD_AGC_TARGET_DBFS = 4,
  // `agc_max_gain_db` is outside 0 to 60, or not finite.
  RR_DR60_SETTING_FIELD_AGC_MAX_GAIN_DB = 5,
  // `agc_max_attenuation_db` is outside 0 to 40, or not finite.
  RR_DR60_SETTING_FIELD_AGC_MAX_ATTENUATION_DB = 6,
  // `agc_attack_ms` is outside 1 to 100, or not finite.
  RR_DR60_SETTING_FIELD_AGC_ATTACK_MS = 7,
  // `agc_release_ms` is outside 50 to 10000, or not finite.
  RR_DR60_SETTING_FIELD_AGC_RELEASE_MS = 8,
  // `vas_mode` is not an `RrDr60VasMode` value (status `INVALID_ARGUMENT`; spec 003).
  RR_DR60_SETTING_FIELD_VAS_MODE = 9,
  // `vas_sensitivity` is outside 1 to 5 (spec 003).
  RR_DR60_SETTING_FIELD_VAS_SENSITIVITY = 10,
  // `vas_threshold_dbfs` is outside -60 to 0, or not finite (spec 003).
  RR_DR60_SETTING_FIELD_VAS_THRESHOLD_DBFS = 11,
  // `vas_hang_ms` is outside 50 to 10000, or not finite (spec 003).
  RR_DR60_SETTING_FIELD_VAS_HANG_MS = 12,
  // `vas_onset_ms` is outside 0 to 200, or not finite (spec 003).
  RR_DR60_SETTING_FIELD_VAS_ONSET_MS = 13,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum RrDr60SettingField RrDr60SettingField;
#else
typedef uint32_t RrDr60SettingField;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Output tap point, passed as `uint32_t` in [`RrDr60Settings::tap`].
enum RrDr60Tap
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // After signal-chain stage 4 (record band-limit).
  RR_DR60_TAP_AFTER_RECORD = 0,
  // After signal-chain stage 10 (playback band-limit). The default.
  RR_DR60_TAP_AFTER_PLAYBACK = 1,
  // After signal-chain stage 3 (AGC). Stages 4 and 10 are not run (spec 002 FR-003).
  RR_DR60_TAP_AFTER_AGC = 2,
  // After signal-chain stage 5 (VAS). Stage 10 is not run (spec 003 FR-003).
  RR_DR60_TAP_AFTER_VAS = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum RrDr60Tap RrDr60Tap;
#else
typedef uint32_t RrDr60Tap;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// What the VAS does with paused audio, passed as `uint32_t` in [`RrDr60Settings::vas_mode`]
// (spec 003 FR-004).
enum RrDr60VasMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // Removed, so the output can be shorter than the input. The default (S-001, A-008).
  RR_DR60_VAS_MODE_DROP = 0,
  // Replaced by silence, so the output keeps the input's length. An emulator option.
  RR_DR60_VAS_MODE_MUTE = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum RrDr60VasMode RrDr60VasMode;
#else
typedef uint32_t RrDr60VasMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Opaque pipeline handle.
typedef struct RrDr60Pipeline RrDr60Pipeline;

// Pipeline settings. Start from `rr_dr60_settings_default` and change fields as needed.
//
// AGC levels use the AES17 convention (a full-scale sine is 0 dBFS). AGC ranges are
// inclusive; out-of-range or non-finite values are rejected even when the AGC is off.
typedef struct RrDr60Settings {
  // Must be `sizeof(RrDr60Settings)`. Lets the struct grow in later versions.
  uint32_t struct_size;
  // Host sample rate in Hz: 8000, 16000, 44100, 48000, 88200 or 96000.
  uint32_t host_rate_hz;
  // Signal-chain stage 4 on (true, default) or bypassed.
  bool record_stage_enabled;
  // Signal-chain stage 10 on (true, default) or bypassed.
  bool playback_stage_enabled;
  // An `RrDr60Tap` value.
  uint32_t tap;
  // Seed for stochastic stages. No effect on output in this version.
  uint64_t seed;
  // Signal-chain stage 3 (AGC) on (true, default; assumed always active, A-020) or bypassed.
  bool agc_enabled;
  // AGC target level in dBFS. Default -10 (A-017). Range -30 to 0.
  float agc_target_dbfs;
  // AGC maximum gain in dB. Default 40 (A-017). Range 0 to 60. A loud first sound after
  // create, reset or long silence can exceed full scale by up to this much: limit or clip
  // before converting to integer PCM.
  float agc_max_gain_db;
  // AGC maximum attenuation in dB (positive). Default 20 (A-017). Range 0 to 40.
  float agc_max_attenuation_db;
  // AGC attack time in ms. Default 10 (A-018). Range 1 to 100.
  float agc_attack_ms;
  // AGC release time in ms. Default 1000 (A-018). Range 50 to 10000.
  float agc_release_ms;
  // Signal-chain stage 5 (VAS) on (true, default; the device has no VAS switch, S-001, A-008)
  // or bypassed.
  bool vas_enabled;
  // An `RrDr60VasMode` value. Default `RR_DR60_VAS_MODE_DROP`: paused audio is removed, so
  // read `RrDr60BlockInfo.produced`.
  uint32_t vas_mode;
  // Microphone sensitivity level. Default 3 (S-001, A-021). Range 1 to 5. Moves only the VAS
  // threshold in this version, 3 dB per level (A-022).
  uint32_t vas_sensitivity;
  // VAS threshold at sensitivity 3, dBFS (sine peak). Default -18 (A-022). Range -60 to 0.
  float vas_threshold_dbfs;
  // VAS hang time in ms. Default 1000 (A-023). Range 50 to 10000.
  float vas_hang_ms;
  // VAS onset time in ms. Default 20 (A-024). Range 0 to 200.
  float vas_onset_ms;
} RrDr60Settings;

// The result of one `rr_dr60_process` call (spec 003 FR-004, FR-005).
typedef struct RrDr60BlockInfo {
  // Output samples written to `output[0 .. produced)`. Never more than `frames`. With the VAS
  // in drop mode (the default) it can be smaller, or 0.
  uintptr_t produced;
  // VAS events this block generated (splices in drop mode, muted regions in mute mode).
  uintptr_t events;
  // The VAS is paused at the end of the block.
  bool paused;
} RrDr60BlockInfo;

// A VAS splice (drop mode) or muted region (mute mode), from `rr_dr60_process_with_events`
// (spec 003 FR-005).
typedef struct RrDr60VasEvent {
  // Drop mode: stream output index of the first sample after the splice. Mute mode: stream
  // output index of the region's first muted sample. Counted from create, reset or
  // reconfigure, so it does not depend on block sizes.
  uint64_t output_position;
  // Drop mode: host input samples removed at this splice. Mute mode: the region's length.
  uint64_t input_length;
} RrDr60VasEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Default settings for `host_rate_hz` (not validated): AGC and VAS on with the assumed device
// values, both band-limit stages on, tap after playback, seed 0. Never fails.
struct RrDr60Settings rr_dr60_settings_default(uint32_t host_rate_hz);

// Creates a pipeline. On success, writes the new handle to `*out_pipeline`. Not real-time
// safe (allocates).
//
// # Safety
//
// `settings` must be NULL or point to a valid `RrDr60Settings`. `out_pipeline` must be NULL
// or point to writable storage for one pointer.
RrDr60Status rr_dr60_create(const struct RrDr60Settings *settings,
                            struct RrDr60Pipeline **out_pipeline);

// Destroys a pipeline. NULL is a no-op.
//
// # Safety
//
// `pipeline` must be NULL or a handle from `rr_dr60_create` that has not been destroyed.
// It must not be used afterwards.
void rr_dr60_destroy(struct RrDr60Pipeline *pipeline);

// Processes `frames` samples from `input` into `output`. Real-time safe.
//
// Only `output[0 .. produced)` holds output: with the VAS in drop mode (the default), pauses
// are removed, so `produced` can be smaller than `frames`, or 0 (spec 003 FR-004).
// `out_info` may be NULL. When it is not, it is always written: on an error, a poisoned handle
// or `frames == 0` it gets `produced = 0`, `events = 0` and the current `paused` value
// (`false` for a NULL handle).
//
// `input == output` processes in place. Any other overlap returns
// [`RrDr60Status::InvalidArgument`]. With `frames == 0`, both buffers may be NULL.
//
// # Safety
//
// `pipeline` must be a live handle. When `frames > 0`, `input` must be readable and
// `output` writable for `frames` floats. `out_info` must be NULL or writable.
RrDr60Status rr_dr60_process(struct RrDr60Pipeline *pipeline,
                             const float *input,
                             float *output,
                             uintptr_t frames,
                             struct RrDr60BlockInfo *out_info);

// As `rr_dr60_process`, and writes the block's VAS events (splices in drop mode, muted
// regions in mute mode) to `events`: the first `events_capacity` of them, in order.
// `out_info->events` counts all of them, so a count above `events_capacity` means some were
// not written; `rr_dr60_max_events` gives a capacity that is always enough. `events` may be
// NULL only when `events_capacity` is 0. Real-time safe (spec 003 FR-005, FR-014).
//
// # Safety
//
// As `rr_dr60_process`; additionally, when `events_capacity > 0`, `events` must be writable
// for that many `RrDr60VasEvent` values.
RrDr60Status rr_dr60_process_with_events(struct RrDr60Pipeline *pipeline,
                                         const float *input,
                                         float *output,
                                         uintptr_t frames,
                                         struct RrDr60BlockInfo *out_info,
                                         struct RrDr60VasEvent *events,
                                         uintptr_t events_capacity);

// Writes to `*out_capacity` an `events_capacity` that is always enough for a block of `frames`
// input samples with the pipeline's current settings (spec 003 research R-07). Never
// allocates; real-time safe. On a non-OK status `*out_capacity` is untouched (rule 2).
//
// # Safety
//
// `pipeline` must be a live handle. `out_capacity` must be NULL or writable.
RrDr60Status rr_dr60_max_events(const struct RrDr60Pipeline *pipeline,
                                uintptr_t frames,
                                uintptr_t *out_capacity);

// Writes the pipeline's fixed latency, in host-rate samples, to `*out_samples`.
//
// # Safety
//
// `pipeline` must be a live handle. `out_samples` must be NULL or writable.
RrDr60Status rr_dr60_latency_samples(const struct RrDr60Pipeline *pipeline, uint32_t *out_samples);

// Returns the pipeline to its freshly created state and clears a poisoned handle.
// Real-time safe.
//
// # Safety
//
// `pipeline` must be a live handle.
RrDr60Status rr_dr60_reset(struct RrDr60Pipeline *pipeline);

// Applies new settings and resets all state, as if the pipeline were created anew. On
// success a poisoned handle becomes usable again. On error the pipeline is unchanged. Not
// real-time safe (allocates).
//
// # Safety
//
// `pipeline` must be a live handle. `settings` must be NULL or point to a valid
// `RrDr60Settings`.
RrDr60Status rr_dr60_reconfigure(struct RrDr60Pipeline *pipeline,
                                 const struct RrDr60Settings *settings);

// Checks `settings` without creating a pipeline. Returns exactly the status
// `rr_dr60_create` would return for them and, if `out_field` is not NULL, writes the field
// at fault there (`RR_DR60_SETTING_FIELD_NONE` when the status is OK). Fields are checked in
// the order struct size, tap, VAS mode, host rate, the AGC fields, then the VAS fields. Never allocates; real-time safe.
//
// # Safety
//
// `settings` must be NULL or point to a valid `RrDr60Settings`. `out_field` must be NULL or
// writable.
RrDr60Status rr_dr60_settings_validate(const struct RrDr60Settings *settings,
                                       RrDr60SettingField *out_field);

// The library version as a static NUL-terminated string, e.g. `"0.1.0"`. Never NULL; do not
// free.
const char *rr_dr60_version_string(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RR_DR60_H */
