/*
 * rr_dr60.h — C API for rr-dr60-emu, a software emulator of the Panasonic RR-DR60 voice
 * recorder's audio signal chain. GENERATED by cbindgen from crates/rr_dr60_ffi — do not edit.
 *
 * Contract (specs/001-pipeline-skeleton/contracts/c-api.md):
 *  1. Errors are values. No function aborts or unwinds into the caller. A caught internal
 *     error returns RR_DR60_STATUS_INTERNAL_ERROR and poisons the handle until
 *     rr_dr60_reset (or rr_dr60_reconfigure) succeeds.
 *  2. A failed call changes nothing: out-parameters are untouched and state is unchanged.
 *  3. The caller owns all buffers; the library never keeps a pointer after a call returns.
 *     Using a handle after rr_dr60_destroy is undefined behavior.
 *  4. A handle must not be used by two threads at the same time; separate handles are
 *     independent.
 *  5. RrDr60Settings only grows at the end; always start from rr_dr60_settings_default().
 *
 * Real-time safe: rr_dr60_process, rr_dr60_reset, rr_dr60_latency_samples.
 * Not real-time safe (allocate): rr_dr60_create, rr_dr60_destroy.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef RR_DR60_H
#define RR_DR60_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// Library major version (equal to the Rust crate's).
#define RR_DR60_VERSION_MAJOR 0

// Library minor version.
#define RR_DR60_VERSION_MINOR 1

// Library patch version.
#define RR_DR60_VERSION_PATCH 0

// Result of every fallible C API call.
enum RrDr60Status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // Success.
  RR_DR60_STATUS_OK = 0,
  // A required pointer was NULL.
  RR_DR60_STATUS_NULL_POINTER = 1,
  // `host_rate_hz` is not a supported host rate.
  RR_DR60_STATUS_UNSUPPORTED_HOST_RATE = 2,
  // Invalid tap value, too-small `struct_size`, or partially overlapping buffers.
  RR_DR60_STATUS_INVALID_ARGUMENT = 3,
  // An internal error (a caught panic). The handle is poisoned until `rr_dr60_reset`.
  RR_DR60_STATUS_INTERNAL_ERROR = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum RrDr60Status RrDr60Status;
#else
typedef int32_t RrDr60Status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Output tap point, passed as `uint32_t` in [`RrDr60Settings::tap`].
enum RrDr60Tap
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // After signal-chain stage 4 (record band-limit).
  RR_DR60_TAP_AFTER_RECORD = 0,
  // After signal-chain stage 10 (playback band-limit). The default.
  RR_DR60_TAP_AFTER_PLAYBACK = 1,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum RrDr60Tap RrDr60Tap;
#else
typedef uint32_t RrDr60Tap;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Opaque pipeline handle.
typedef struct RrDr60Pipeline RrDr60Pipeline;

// Pipeline settings. Start from `rr_dr60_settings_default` and change fields as needed.
typedef struct RrDr60Settings {
  // Must be `sizeof(RrDr60Settings)`. Lets the struct grow in later versions.
  uint32_t struct_size;
  // Host sample rate in Hz: 8000, 16000, 44100, 48000, 88200 or 96000.
  uint32_t host_rate_hz;
  // Signal-chain stage 4 on (true, default) or bypassed.
  bool record_stage_enabled;
  // Signal-chain stage 10 on (true, default) or bypassed.
  bool playback_stage_enabled;
  // An `RrDr60Tap` value.
  uint32_t tap;
  // Seed for stochastic stages. No effect on output in this version.
  uint64_t seed;
} RrDr60Settings;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Default settings for `host_rate_hz` (not validated): both stages on, tap after playback,
// seed 0. Never fails.
struct RrDr60Settings rr_dr60_settings_default(uint32_t host_rate_hz);

// Creates a pipeline. On success, writes the new handle to `*out_pipeline`. Not real-time
// safe (allocates).
//
// # Safety
//
// `settings` must be NULL or point to a valid `RrDr60Settings`. `out_pipeline` must be NULL
// or point to writable storage for one pointer.
RrDr60Status rr_dr60_create(const struct RrDr60Settings *settings,
                            struct RrDr60Pipeline **out_pipeline);

// Destroys a pipeline. NULL is a no-op.
//
// # Safety
//
// `pipeline` must be NULL or a handle from `rr_dr60_create` that has not been destroyed.
// It must not be used afterwards.
void rr_dr60_destroy(struct RrDr60Pipeline *pipeline);

// Processes `frames` samples from `input` into `output`. Real-time safe.
//
// `input == output` processes in place. Any other overlap returns
// [`RrDr60Status::InvalidArgument`]. With `frames == 0`, both buffers may be NULL.
//
// # Safety
//
// `pipeline` must be a live handle. When `frames > 0`, `input` must be readable and
// `output` writable for `frames` floats.
RrDr60Status rr_dr60_process(struct RrDr60Pipeline *pipeline,
                             const float *input,
                             float *output,
                             uintptr_t frames);

// Writes the pipeline's fixed latency, in host-rate samples, to `*out_samples`.
//
// # Safety
//
// `pipeline` must be a live handle. `out_samples` must be NULL or writable.
RrDr60Status rr_dr60_latency_samples(const struct RrDr60Pipeline *pipeline, uint32_t *out_samples);

// Returns the pipeline to its freshly created state and clears a poisoned handle.
// Real-time safe.
//
// # Safety
//
// `pipeline` must be a live handle.
RrDr60Status rr_dr60_reset(struct RrDr60Pipeline *pipeline);

// The library version as a static NUL-terminated string, e.g. `"0.1.0"`. Never NULL; do not
// free.
const char *rr_dr60_version_string(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RR_DR60_H */
