# /// script
# requires-python = ">=3.10"
# dependencies = ["mpmath"]
# ///
"""Generate high-precision reference values for rr_dr60_detmath's unit tests (tasks.md T012).

Each argument is an exact f64. Each reference is computed with mpmath at 60 significant digits
and printed with 25 digits, so Rust parses it to the correctly rounded f64.

Usage (from the repository root):
  uv run tools/detmath-refs/gen_refs.py > crates/rr_dr60_detmath/src/test_refs.rs
"""
import math
import random

from mpmath import mp, mpf

mp.dps = 60
rng = random.Random(0x0D60)


def fmt(x: float) -> str:
    return repr(float(x)) if math.isfinite(x) else str(x)


def emit(name: str, pairs: list[tuple[float, object]]) -> None:
    print(f"pub(crate) const {name}: &[(f64, f64)] = &[")
    for x, y in pairs:
        print(f"    ({fmt(x)}, {mp.nstr(y, 25, strip_zeros=False)}),")
    print("];")
    print()


def trig_args() -> list[float]:
    xs = [0.5, -0.5, 1.0, 2.0, 3.0, 1e-9, -1e-12, 0.785398, 100.0, 1000.0, 9999.5, -9999.5]
    for k in (1, 2, 3, 4, 7, 100, 1001, 6366):  # multiples of pi/2, the hardest reduction cases
        base = k * math.pi / 2
        xs += [base, math.nextafter(base, math.inf), -base]
    while len(xs) < 72:
        xs.append(rng.uniform(-1e4, 1e4))
    return xs


print("//! GENERATED by tools/detmath-refs/gen_refs.py — do not edit.")
print("//! High-precision references (mpmath, 60 digits) for the detmath unit tests (tasks.md T012).")
print("// 25 digits on purpose: Rust parses each literal to the correctly rounded f64.")
print("// Arguments are exact f64 multiples of pi/2 by design (hardest reduction cases).")
print("#![allow(clippy::excessive_precision, clippy::approx_constant)]")
print()
xs = trig_args()
emit("SIN_REFS", [(x, mp.sin(mpf(x))) for x in xs])
emit("COS_REFS", [(x, mp.cos(mpf(x))) for x in xs])
ex = [0.0, 1.0, -1.0, 0.5, 1e-10, 700.0, -700.0, 709.0, -708.0, 0.6931471805599453]
while len(ex) < 64:
    ex.append(rng.uniform(-700.0, 700.0))
emit("EXP_REFS", [(x, mp.exp(mpf(x))) for x in ex])
lx = [1.0, 2.0, 0.5, 10.0, 1e-300, 1e300, 0.7071067811865476, 1.4142135623730951, 1.0000000001]
while len(lx) < 64:
    lx.append(10.0 ** rng.uniform(-300.0, 300.0))
emit("LN_REFS", [(x, mp.log(mpf(x))) for x in lx])
emit("I0_REFS", [(x, mp.besseli(0, mpf(x))) for x in (0.0, 0.5, 1.0, 2.0, 5.0, 6.76, 10.0, 20.0)])
