//! C API for the `rr_dr60` RR-DR60 signal-chain emulator.
//!
//! This is the language-neutral integration surface (spec FR-023, FR-024) for
//! C, Swift and other languages. The header `include/rr_dr60.h` is generated by
//! cbindgen. The contract is in `specs/001-pipeline-skeleton/contracts/c-api.md`.
//!
//! This is the only crate in the workspace that may use `unsafe`. Every
//! `unsafe` block carries a `// SAFETY:` comment, and every entry point catches
//! panics so that none unwinds into the host.
