# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy", "scipy"]
# ///
"""Design and verify the AGC detector's Hilbert FIR (signal-chain stage 3, spec 002).

Design (specs/002-agc/research.md R-03), at the 8 kHz device rate (A-001):
  * equiripple type-III Hilbert transformer, 63 taps, passband 250-3750 Hz
  * used by the AGC level detector to form the analytic envelope (A-019, R-02)
  * every design constant is an engineering target (R-15), not a device property

The script verifies the design and exits non-zero on any failure:
  * antisymmetric taps (h[k] = -h[62-k]) and exactly-zero odd-index taps (incl. the centre h[31])
  * |H| within +/-0.01 dB at every 10 Hz step from 300 to 3400 Hz
The emitted Rust file stores each coefficient as an exact bit pattern, so the Rust
build never depends on this script's floating-point environment (001 R-04).

Usage (from the repository root):
  uv run tools/filter-design/design_hilbert.py            # design, verify, write coefficients
  uv run tools/filter-design/design_hilbert.py --check    # design and verify only
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np
from scipy import signal

FS = 8000.0  # A-001: device rate
NUM_TAPS = 63  # engineering target (002 R-15)
BAND_HZ = (250.0, 3750.0)  # engineering target (002 R-15)
CHECK_HZ = (300.0, 3400.0)  # spec 002 FR-008 test band
TOLERANCE_DB = 0.01  # engineering target (002 R-15)

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT = REPO_ROOT / "crates/rr_dr60/src/stages/agc_hilbert_coeffs.rs"


def design() -> np.ndarray:
    """Return the 63 Hilbert FIR taps, with odd-index taps forced to exactly 0."""
    h = signal.remez(NUM_TAPS, list(BAND_HZ), [1.0], type="hilbert", fs=FS)
    # Type III centred on tap 31: taps at an even distance from the centre (the odd
    # indices, including h[31]) are zero in theory; remez leaves ~1e-17 residue.
    h[1::2] = 0.0
    # Enforce exact antisymmetry around the centre tap.
    h = 0.5 * (h - h[::-1])
    return h


def verify(h: np.ndarray) -> list[tuple[str, str, str, bool]]:
    rows = []
    rows.append(("tap count", f"{NUM_TAPS}", f"{len(h)}", len(h) == NUM_TAPS))
    anti = bool(np.all(h == -h[::-1]))
    rows.append(("antisymmetric h[k] = -h[62-k]", "exact", "yes" if anti else "no", anti))
    odd_zero = bool(np.all(h[1::2] == 0.0))
    rows.append(("odd-index taps", "exactly 0", "yes" if odd_zero else "no", odd_zero))
    f = np.arange(CHECK_HZ[0], CHECK_HZ[1] + 1.0, 10.0)
    _, resp = signal.freqz(h, worN=f, fs=FS)
    dev = float(np.max(np.abs(20.0 * np.log10(np.abs(resp)))))
    rows.append(("|H| 300-3400 Hz", f"±{TOLERANCE_DB} dB", f"±{dev:.4f} dB", dev <= TOLERANCE_DB))
    return rows


def hexbits(x: float) -> str:
    return "0x" + struct.pack(">d", float(x)).hex()


def render(h: np.ndarray) -> str:
    lines = [
        "//! AGC detector Hilbert FIR coefficients (signal-chain stage 3, spec 002).",
        "//!",
        "//! GENERATED by tools/filter-design/design_hilbert.py — do not edit.",
        "//! Regenerate with: `uv run tools/filter-design/design_hilbert.py`",
        "//!",
        "//! Design (specs/002-agc/research.md R-03), at the 8 kHz device rate (A-001):",
        f"//! - equiripple type-III Hilbert transformer, {NUM_TAPS} taps, passband "
        f"{BAND_HZ[0]:g}-{BAND_HZ[1]:g} Hz",
        f"//! - |H| within ±{TOLERANCE_DB:g} dB from {CHECK_HZ[0]:g} to {CHECK_HZ[1]:g} Hz",
        "//! - forms the analytic envelope of the AGC level detector (A-019, R-02)",
        "//! - all design values are engineering targets (002 R-15)",
        "//!",
        "//! Taps are antisymmetric, and every odd-index tap (including the centre) is exactly 0,",
        "//! so only the 32 even-index taps need multiplying. Each coefficient is",
        "//! stored as an exact bit pattern so it is identical on every platform (001 R-04).",
        "",
        f"/// Hilbert FIR taps, `h[0]` first. The filter's delay is {(NUM_TAPS - 1) // 2} samples.",
        "#[rustfmt::skip]",
        f"pub(crate) const AGC_HILBERT: [f64; {NUM_TAPS}] = [",
    ]
    for k, c in enumerate(h):
        lines.append(f"    f64::from_bits({hexbits(c)}), // h[{k}] = {c:.17e}")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="design and verify only; write nothing")
    args = ap.parse_args()

    h = design()
    rows = verify(h)
    width = max(len(r[0]) for r in rows)
    print("AGC detector Hilbert FIR — research.md R-03 verification")
    for prop, target, measured, ok in rows:
        print(f"  {prop:<{width}}  {target:<12} {measured:<14} {'PASS' if ok else 'FAIL'}")
    failed = [r for r in rows if not r[3]]
    if failed:
        print(f"FAILED: {len(failed)} check(s) not met; nothing written.", file=sys.stderr)
        return 1
    if not args.check:
        OUTPUT.write_text(render(h))
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
